//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleApp1.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja adicionar mais uma distância e direção? [pressione ENTER] [para sair: digite SAIR].
        /// </summary>
        internal static string addDisDir {
            get {
                return ResourceManager.GetString("addDisDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua Coordenada Atual é:.
        /// </summary>
        internal static string coordAtual {
            get {
                return ResourceManager.GetString("coordAtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua Coordenada Inicial é:.
        /// </summary>
        internal static string coordIni {
            get {
                return ResourceManager.GetString("coordIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite sua direção entre [N, S, L, O]:.
        /// </summary>
        internal static string digiteDir {
            get {
                return ResourceManager.GetString("digiteDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite a distância desejada:.
        /// </summary>
        internal static string digiteDis {
            get {
                return ResourceManager.GetString("digiteDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o valor de X:.
        /// </summary>
        internal static string digiteX {
            get {
                return ResourceManager.GetString("digiteX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o valor de Y:.
        /// </summary>
        internal static string digiteY {
            get {
                return ResourceManager.GetString("digiteY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Direção digitada é inválida!.
        /// </summary>
        internal static string direcaoInv {
            get {
                return ResourceManager.GetString("direcaoInv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor digitado é inválido! [digite um número Inteiro].
        /// </summary>
        internal static string erroXeY {
            get {
                return ResourceManager.GetString("erroXeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Intensidade digitada é inválida! [digite um número Inteiro].
        /// </summary>
        internal static string intensInv {
            get {
                return ResourceManager.GetString("intensInv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primeiro digite a Coordenada inicial:.
        /// </summary>
        internal static string partidaInicial {
            get {
                return ResourceManager.GetString("partidaInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculadora de Coordenadas.
        /// </summary>
        internal static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
    }
}
